first commit
KristijonasTaru/bbcWebTesting pull request #1
Opened 2024-05-13 13:44 UTC by KristijonasTaru

2024-05-13 14:24 UTC, orion-baroniunas requested changes
Na reiktu daug kur susitvarkyti dar lokatorius, nes nemazai kur yra neissikeltu, taip pat daug kodo ikelta uzkomentuoto, ta reikia patrint, pasidomek labiau kaip pageObject veikia, nes dabar tu susikurei ta modeli ir isikelei tiesigiog lokatorius, o reiktu ir isiskelti visa puslapiu funkcionaluma pagal puslapius ,tai butu zymiai aiskiau, nes dabar tu visa funkcionaluma rasai testuose.

2024-05-13 14:24 UTC, baroniunas commented on cypress/e2e/bbc-article-viewing/bbc-article-navigation-links.js
> +    cy.get('[data-testid="edinburgh-article"]').first().click();
neisikelei i locators file

2024-05-13 14:24 UTC, baroniunas commented on cypress/e2e/bbc-article-viewing/bbc-article-main.js
> +  const mainFunctions = new MainFunctions();
jeigu klasese kurtum static metodus, nereiktu kurtis naujo instance kiekviena kart

2024-05-13 14:24 UTC, baroniunas commented on cypress/e2e/bbc-article-viewing/bbc-article-main.js
> +// possible header - "section[data-component='headline-block']" westminster-card Vermont-grid manchester-card edinburgh-card
istrink nereikialingus line

2024-05-13 14:24 UTC, baroniunas commented on cypress/e2e/bbc-article-viewing/bbc-article-main.js
> +      cy.get('div[data-component="text-block"]').should('have.css', "margin", "0px 591.5px 16px")
ka daro tavo sitas assertas? kodel butent tokie pixeliai

2024-05-13 14:24 UTC, orion-baroniunas commented on cypress/e2e/bbc-article-viewing/bbc-article-navigation-links.js
> +      `nav li[data-testid$='mainNavigationItemStyled']`,
issikelk irgi locatoriu

2024-05-13 14:24 UTC, baroniunas commented on cypress/e2e/bbc-article-viewing/bbc-article-navigation-links.js
> +//   });
sito gal nereik ?

2024-05-13 14:24 UTC, orion-baroniunas commented on cypress/e2e/bbc-home-navigation/bbc-home-footer-informative.js
> +    mainFunctions.assertURL("usingthebbc/cookies");
o cia ji isidedi vel i vidu

2024-05-13 14:24 UTC, orion-baroniunas commented on cypress/e2e/bbc-home-navigation/bbc-home-navbar.js
> +  });
siaip sita funkcija gali atskirai issiklet nes du kart perpanaudoji ir perrasineji taip pat viska

2024-05-13 14:24 UTC, baroniunas commented on cypress/support/pageObject/Main_Functions.js
> +      );
cia visi mygtukai irgi eina i locatorius, nes neaisku,

2024-05-13 14:24 UTC, baroniunas commented on cypress/e2e/language-selection/language-selection.js
> +    // );
pratrint

2024-05-13 14:24 UTC, baroniunas commented on cypress/e2e/language-selection/language-selection.js
> +    );
assertion message galima isisikelt prie language locatoriu ir butu aiskiau, bei maziau magic stringu

2024-05-13 14:24 UTC, baroniunas commented on cypress/support/commands.js
> +// Cypress.Commands.overwrite('visit', (originalFn, url, options) => { ... })
ar reikia sio failo jeigu jis tuscias, ir nenaudoji custom komandu ?

2024-05-13 14:24 UTC, baroniunas commented on cypress/e2e/bbc-responsive-design/bbc-responsive-design.js
> +    mainFunctions.beforeEachRoutine();
kodel nusprendei dabar kitaip naudot nei visur ir kiekvienam teste rasyti po siia eilute, o ne sudeti i beforeeach hooka

2024-05-13 14:24 UTC, baroniunas commented on cypress/e2e/bbc-responsive-design/bbc-responsive-design.js
> +      "924px 308px"
kodel butent sitas assertas parodo ar teisingai uzkrauna ?

2024-05-13 14:24 UTC, baroniunas commented on cypress/e2e/bbc-responsive-design/bbc-responsive-design.js
> +    cy.get(homeLocators.MAIN_PAGE_GRID).should(
tai cia visas sitas gali eit viena kart parasytas i before each hooka, o it scope gali rasyt tiesiog asserta ir bus zymiai more clean ir maziau codo

2024-05-13 14:24 UTC, baroniunas commented on cypress/support/pageObject/Main_Functions.js
> +  }
nelabai tinka pavadinimas siai funkcija

2024-05-13 14:24 UTC, baroniunas commented on cypress/support/pageObject/Main_Functions.js
> +  }
cia irgi, turetu but kazkas panasaus closePopUpWindow

2024-05-13 14:24 UTC, baroniunas commented on cypress/e2e/bbc-video-player/bbc-video-player.js
> +  //   });
delete

2024-05-14 10:59 UTC, KristijonasTaru reviewed
Atsakyti komentarai

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/e2e/bbc-article-viewing/bbc-article-main.js
> +      cy.get('div[data-component="text-block"]').should('have.css', "margin", "0px 591.5px 16px")
Pakoregavau sita assert: pagal ideja jis ima text block ir pagal css paziuri ar jis iscentruotas, pakeiciau it("Verify that article is centred") nes confusing pavadinimas

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/e2e/bbc-article-viewing/bbc-article-navigation-links.js
> +    cy.get('[data-testid="edinburgh-article"]').first().click();
jau perkeltas

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/e2e/bbc-article-viewing/bbc-article-navigation-links.js
> +      `nav li[data-testid$='mainNavigationItemStyled']`,
irgi iskeltas, visi main function locatoriai iskelti i atskira faila, tai dabar del locatoriu tik paliksiu komentara i atsakyta

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/e2e/bbc-article-viewing/bbc-article-navigation-links.js
> +//   });
jau istryniau, pries keliant galvojau apie kita approach taciau nusprendziau likti su turimu

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/e2e/bbc-home-navigation/bbc-home-footer-informative.js
> +    mainFunctions.assertURL("usingthebbc/cookies");
cia pirma funkcija paspaudzia ant reikalingo link 
antra funkcija assert padaro ar url teisingas

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/e2e/bbc-home-navigation/bbc-home-navbar.js
> +  });
iskelta i main functions

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/e2e/bbc-responsive-design/bbc-responsive-design.js
> +    mainFunctions.beforeEachRoutine();
butent cia testuoju pagal resoliucijas tai ispradziu uzkraunu teisingos rezoliucijos langa kiekvienam atskiram testui ir poto kaip jis uzkrautas darau veiksmus

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/e2e/bbc-responsive-design/bbc-responsive-design.js
> +      "924px 308px"
paziurejau, kad kiekvienas resoliucijos pakitimas (it surasytos rezoliucijos) turi savo skirtinga grid, kadangi desktop ir tablet versijos abi turi register ir sign in button nusprendziau tikrinti pagal grid nes abieju skirasi elementu isdestymas

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/e2e/bbc-responsive-design/bbc-responsive-design.js
> +    cy.get(homeLocators.MAIN_PAGE_GRID).should(
kaip ir pries tai minejau as visuose pirma nustatau viewport and kokios rezoliucijos uzsikrauna ir tada tikrinu ar teisingai isdestyti componentai joje

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/e2e/bbc-video-player/bbc-video-player.js
> +  //   });
sita uzkomentuota koda paliksiu pristatymui, kad galeciau placiau apie video player papasakoti kokie challange buvo ir ko nepavyko padaryti ir kodel

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/e2e/language-selection/language-selection.js
> +    // );
istrintas

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/support/commands.js
> +// Cypress.Commands.overwrite('visit', (originalFn, url, options) => { ... })
sitie yra cypress sukurti failai, tai neesu isitikines ar jie butini, bet jei kada pradesi naudoti savo testuose komandas butu patogu jei jie butu ir nereiktu is naujo ju kurti

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/support/pageObject/Main_Functions.js
> +  }
pervadintas

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/support/pageObject/Main_Functions.js
> +      );
jau perkelti i nauja faila kur visi main lokatoriai

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/support/pageObject/Main_Functions.js
> +  }
sita funkcija handlina video player mygtuku paspaudimus, kad nereiktu kartoti, tai ir pavadinima palikau video handller

2024-05-14 10:59 UTC, KristijonasTaru commented on cypress/support/pageObject/Main_Functions.js
> +  }
pakeiciau pavadinima i clickVideoPlayerButton

2024-05-15 07:03 UTC, KristijonasTaru commented on cypress/e2e/bbc-article-viewing/bbc-article-main.js
> +  const mainFunctions = new MainFunctions();
kitame git push bus pakeista i static

2024-05-15 13:00 UTC, orion-baroniunas approved these changes, later dismissed

2024-05-16 10:10 UTC, RytisMiciunas approved these changes, later dismissed

2024-05-20 08:54 UTC, merged